---
title: "Computational Statistics Computer Lab 4 (Group 7)"
author: 
  - Qinyuan Qi(qinqi464)
  - Satya Sai Naga Jaya Koushik	Pilla (satpi345)
date: "`r Sys.Date()`"
output: pdf_document
---

## Question 1:  Computations with Metropolis–Hastings (Solved by )

### Answer:

```{r setup1, include=FALSE}
########################## Init code for question 1 ############################
rm(list = ls())
```

### (1.a)

```{r 1a}
########################## [ 1.a ] #############################################

```

### (1.b)

```{r 1b}
########################## [ 1.b ] #############################################

```

### (1.c)

```{r 1c}
########################## [ 1.c ] #############################################

```

### (1.d)

```{r 1d}
########################## [ 1.d ] #############################################

```

### (1.e)

```{r 1e}
########################## [ 1.e ] #############################################

```

### (1.f)

```{r 1f}
########################## [ 1.f ] #############################################

```

## Question 2:  Gibbs sampling (Solved by )

### Answer:

```{r setup2, include=FALSE}
########################## Init code for question 1 ############################
rm(list = ls())
```

### (2.a)

```{r 2a}
########################## [ 2.a ] #############################################

```

### (2.b)

```{r 2b}
########################## [ 2.b ] #############################################

```
### (2.c)

```{r 2c}
########################## [ 2.c ] #############################################

```

### (2.d)

```{r 2d}
########################## [ 2.d ] #############################################

```

### (2.e)

```{r 2e}
########################## [ 2.e ] #############################################

```

\newpage
# Appendix: Code for this report

```{r ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE}
```
