---
title: "Computational Statistics Computer Lab 6 (Group 7)"
author: 
  - Qinyuan Qi(qinqi464)
  - Satya Sai Naga Jaya Koushik	Pilla (satpi345)
date: "`r Sys.Date()`"
output: pdf_document
---

## Question 1: Genetic algorithm (Solved by Qinyuan Qi)

### Answer:

### (1):

### (2):

### (3):

### (4):

### (5):

### (6):

### (7):

### (8):

### (9):

## Question 2: EM algorithm (Solved by Satya Sai Naga Jaya Koushik Pilla)

### Answer:

```{r setup2, include=FALSE}
########################## Init code for question 1 ############################
rm(list = ls())
library(ggplot2)
set.seed(12345)
```
### (1) Plot 2 histograms:

According to the plots generated, we found that the plot seems follow exponential distribution.

```{r 2.1}
################################## (2.1) #######################################
# Load data
data <- read.csv("censoredproc.csv", 
                sep = ";", header = TRUE)
# We will filter out the records with cens = 2
filtered_data <- data[data$cens != 2,]
layout(matrix(c(1:2), 1, 2))
# plot the data
hist(data$time, breaks = 100, main="Hist of filtered data")
# plot the filtered data
hist(filtered_data$time, breaks = 100, main="Hist of filtered data")
```

### (2):

The general PDF form of an exponential distribution is:

$$
f(x,\lambda) = \begin{cases} \lambda e^{\lambda x} & x \geq 0 \\ 0 & x < 0 \end{cases}
$$

### (3):

### (4):

### (5):

### (6):
